#!/usr/bin/env zsh

if (( ${+_z4h_redraw_fd} )); then
  zle -F "$_z4h_redraw_fd"
  exec {_z4h_redraw_fd}>&-
  unset _z4h_redraw_fd
fi

if [[ -v region_highlight &&
      ( ${LASTWIDGET-} != accept-line || ${WIDGET-} != zle-line-pre-redraw ) ]]; then
  # Save zsh-sage's highlight before _zsh_highlight rebuilds region_highlight
  # from scratch, which would wipe out the confidence-colored ghost text.
  local _z4h_sage_hl="${_SAGE_LAST_HIGHLIGHT-}"
  local _z4h_sage_pd="${POSTDISPLAY-}"
  _zsh_highlight
  # Restore zsh-sage's highlight entry if there was one.
  if [[ -n "$_z4h_sage_hl" ]]; then
    _SAGE_LAST_HIGHLIGHT="$_z4h_sage_hl"
    POSTDISPLAY="$_z4h_sage_pd"
    region_highlight+=("$_z4h_sage_hl")
  fi
fi
